### PR TITLE
fix(renderer): stop blank white window from Node process-table import

### LINKED ISSUE #18812: Linux from-source: blank white window from Node process/promisify in sandboxed renderer
## Summary

Building and launching Orca from source on Linux (Electron sandboxed renderer) can show a blank white main window.

Console:
```
Uncaught ReferenceError: process is not defined
Uncaught TypeError: promisify is not a function
```

## How we found it

Smoke-testing from-source Orca on Omarchy (Arch, Wayland) with Electron 43. Separately, Wayland can hit Chromium GPU FATAL/SIGILL without X11/no-sandbox/disable-gpu flags (environmental, out of scope). With a surviving GPU path, the window stayed white due to the renderer importing process-table-snapshot-reader (Node promisify/execFile + module-load process.platform) only to read a 500ms TTL constant.

## Root cause

- sandbox:true renderer has no Node process
- agent-completion-poll-interval.ts imports PROCESS_TABLE_SNAPSHOT_MAX_STALENESS_MS from process-table-snapshot-reader.ts
- Introduced in #18742

## Related

Fork proof: https://github.com/jondmarien/orca/pull/9

### PR DESCRIPTION
**Pull request by jondmarien**
## ELI5

The Linux desktop window could come up blank because the sandboxed renderer loaded a Node-only process-table helper. That helper reads `process.platform` and then calls `util.promisify` / `execFile('ps')`. Chromium has no Node `process` or `promisify`, so module evaluation threw and killed the UI.

This PR moves the 500ms TTL onto the parser/constants module, guards module-load `process.platform` reads, and stops the renderer poll-interval from importing the Node `ps` reader.

A separate Wayland GPU crash (`GPU process isn't usable` / SIGILL) is environmental and is **not** fixed here.

## What Changed

- Moved `PROCESS_TABLE_SNAPSHOT_MAX_STALENESS_MS` (500) onto `src/shared/process-table-snapshot.ts` (parser/constants; no `ps` exec).
- Pointed `agent-completion-poll-interval.ts` at `process-table-snapshot.ts` instead of `process-table-snapshot-reader.ts`.
- Re-exported the TTL from the reader for main/relay callers.
- Guarded `PS_ARGS` and `CHEAP_PS_ARGS` with `typeof process !== 'undefined' ? process.platform : ''` (typeof-guard alone is not enough — `promisify` still threw until the reader import was cut).
- Added `process-table-snapshot-renderer-eval.test.ts` (evaluate snapshot module with `process` deleted; assert poll-interval does not import the exec reader).

**Scope:** white-screen fix only — no Orca-1…5 / focus / sidecar.

Reproduced on Omarchy / Arch Wayland: `Uncaught ReferenceError: process is not defined` in `out/renderer/assets/web-session-tabs-sync-*.js`. After a local `typeof process` guard on `PS_ARGS` only, the same chunk threw `promisify is not a function`.

Vite named the chunk after `web-session-tabs-sync`, but the throw was module evaluation after:

`agent-completion-poll-interval.ts` → `process-table-snapshot-reader.ts` → `process-table-snapshot.ts`

The renderer only needs the 500ms TTL. Pulling the Node capture stack into the sandbox is the bug.

## Linked Issue

Fixes #18812

## Visual Proof

N/A — no visual or interaction change. The window that previously stayed white should now paint; layout and styling are unchanged.

## Testing

- [x] Automated tests added/updated
- [ ] I did not relaunch the Electron app on a Wayland desktop in this environment

```text
pnpm test src/shared/process-table-snapshot-renderer-eval.test.ts \
  src/shared/process-table-snapshot.test.ts \
  src/renderer/src/components/terminal-pane/agent-completion-poll-interval.test.ts
```

48 tests passed, including the sandbox-eval and full import-boundary cases.

Also passed locally: `pnpm run check:code-quality:changed`, `pnpm run tc:node`, `pnpm run tc:web`.

**Not this PR:** Chromium `FATAL: GPU process isn't usable` / SIGILL without enough GPU/ozone flags on Wayland. Use the existing Linux flags (`--ozone-platform=x11 --disable-gpu`, etc.) if the GPU process dies; that path is environmental.

## AI Disclosure

Cursor Grok 4.6 (cloud agent).

## Review

- **Cross-platform:** `PS_ARGS` still selects Darwin `lstart=` vs Linux/Windows `etimes=` when Node `process` exists. The renderer never evaluates that module now.
- **SSH / folder workspaces:** process-table capture still runs on the execution host via the reader. Only the renderer import graph changed.
- **Git providers / agents:** unaffected.
- **Performance:** no extra `ps` forks; TTL remains 500ms.
- **Security:** renderer no longer bundles the Node exec reader or snapshot parser for this constant.
- **UI:** no STYLEGUIDE change.

## Agent skill upstream boundary

- [x] Not applicable, or this change follows `docs/reference/agent-skill-sharing-upstream-boundary.md` and copies or mechanically translates no upstream skill-installer source, tests, fixtures, registry entries, path tables, comments, or documentation.

## Notes

No README / CONTRIBUTING Linux-run note: those docs have a generic `pnpm dev` setup, not a Linux electron-flags section. The GPU/ozone failure is called out above as out of scope.

## Checklist

- [x] This PR is small and focused
- [x] I explained what changed and why (including ELI5)
- [x] Before/after screenshots or videos attached for UI changes, or `N/A` with reason
- [x] Self-reviewed for correctness, security, and performance
- [x] Cross-platform, SSH/remote, and path/shortcut impact considered (or N/A)
- [x] Targeted tests, changed-file quality, `tc:node`, and `tc:web` passed; full `pnpm lint` / `pnpm test` / `pnpm build` left to CI

<div><a href="https://cursor.com/agents/bc-f7a99adb-608c-4a6c-b318-2f10d8709640?cursor_ref=pr_footer&cursor_cta=open_in_web"><picture><source media="(prefers-color-scheme: dark)" srcset="https://cursor.com/assets/images/open-in-web-dark.png"><source media="(prefers-color-scheme: light)" srcset="https://cursor.com/assets/images/open-in-web-light.png">Open in Web</picture></a>&nbsp;<a href="https://cursor.com/background-agent?bcId=bc-f7a99adb-608c-4a6c-b318-2f10d8709640&cursor_ref=pr_footer&cursor_cta=open_in_cursor"><picture><source media="(prefers-color-scheme: dark)" srcset="https://cursor.com/assets/images/open-in-cursor-dark.png"><source media="(prefers-color-scheme: light)" srcset="https://cursor.com/assets/images/open-in-cursor-light.png">Open in Cursor</picture></a>&nbsp;</div>

### CODE REVIEW

**Comment by jondmarien** [comment]
Closing in favor of maintainer fix https://github.com/stablyai/orca/pull/18814 — same sandboxed-renderer white-screen / process-table import issue. Thanks for catching it!
