### PR TITLE
fix(renderer): stop a shared poll-interval constant white-screening the app

### PR DESCRIPTION
**Pull request by nwparker**
| | Files | Added | Deleted | Net |
| :--- | ---: | ---: | ---: | ---: |
| Test | 1 | $\color{#1a7f37}{\Huge{\mathbf{+}}}$​120 | 0 | $\color{#1a7f37}{\Huge{\mathbf{+}}}$​120 |
| Prod | 3 | $\color{#1a7f37}{\Huge{\mathbf{+}}}$​17 | $\color{#cf222e}{\Huge{\mathbf{−}}}$​7 | $\color{#1a7f37}{\Huge{\mathbf{+}}}$​10 |

## The bug

`1.4.198-hourly.202609050816` launches to a fully white window. `<div id="root">` is empty; nothing mounts.

Attaching CDP to the packaged app:

```
[pageerror] ReferenceError: process is not defined
    at .../out/renderer/assets/web-session-tabs-sync-ABfGRZ9n.js:1:68349
```

Shimming `globalThis.process` advances it exactly one step, to the next Node stub — `(0, it(...).promisify) is not a function` — which pins the offending module.

## Root cause

**Broken by #18742 (`e1599c94b8b`, "perf(terminals): let idle panes share one process-table capture instead of forking their own", merged 2026-09-05 00:05 PDT).** It added `agent-completion-poll-interval.ts`, which imports one constant from `shared/process-table-snapshot-reader`. That reader is main-process-only:

```
main.tsx → App.tsx → … → agent-completion-poll-scheduler.ts
        → agent-completion-poll-interval.ts
        → shared/process-table-snapshot-reader.ts   (node:child_process, node:fs/promises, node:util)
        → shared/process-table-snapshot.ts          (top-level `process.platform`)
```

`process-table-snapshot.ts` spends `process.platform` at module scope to pick its `ps` argv. The renderer is sandboxed — no `process` — so the entry chunk throws during evaluation and React never gets to render.

Nothing in #18742's own logic is wrong; the perf change is fine. The single import line is the whole defect. Every gate was green because Vite stubs `node:*` instead of failing the build, so it typechecked, tested, packaged, signed, and shipped.

## Fix

- `shared/process-table-snapshot-ttl.ts` — new leaf module, zero imports, owns the TTL and `PROCESS_TABLE_SNAPSHOT_MAX_STALENESS_MS`.
- `process-table-snapshot-reader.ts` imports and re-exports it, so main-side callers are untouched.
- `agent-completion-poll-interval.ts` imports the leaf module.

## Guard

`renderer-node-builtin-import-boundary.test.ts` walks the renderer's real module graph from `main.tsx` and fails on any reachable `node:` builtin, printing the full import chain:

```
src/shared/process-table-snapshot-reader.ts imports node:child_process
  via src/renderer/src/main.tsx
   -> src/renderer/src/App.tsx
   -> src/renderer/src/app-shell/use-app-shell-services.ts
   ...
   -> src/renderer/src/components/terminal-pane/agent-completion-poll-interval.ts
   -> src/shared/process-table-snapshot-reader.ts
```

Seeded from the entry rather than from every renderer file on purpose — reachability is the property that matters. A `*.test-support.ts` may import `node:path` freely as long as nothing shipped reaches it.

The second commit fixes two blind spots found while reviewing the first: the walker only followed relative specifiers and required a `from`, so it missed the 10,828 `@/`-aliased imports the renderer actually uses, and every bare `import './x'` — the exact shape that runs module-level code. Coverage: 5,122 → 6,323 reachable modules.

## Verification

- Root cause reproduced live against the installed 1.4.198 build via CDP, not inferred from the diff.
- Ratchet verified red on the unpatched tree (chain above) and green after.
- `process-table-snapshot.ts` and its reader are no longer renderer-reachable.
- `pnpm tc` clean, `oxlint` clean, related tests pass.

### CODE REVIEW

**Comment by nwparker** [comment]
Superseded by #18814, which landed the same fix ~25 minutes before this and does it better:

- puts the constant in `process-table-snapshot.ts` (the environment-neutral half of the existing pair) rather than introducing a third module for it;
- guards **both** `ps` argv reads behind `typeof process`, so a future renderer import of that module is harmless rather than fatal — this PR only moved the constant out of reach;
- catches that #18780 added a *second* module-scope `process.platform` read next to the first, which this PR missed;
- walks `main.tsx`, `popout.tsx` and `web/main.tsx` including lazy routes, where this PR's ratchet walked only `main.tsx`, and adds a self-check asserting the graph is real so an empty offender list means something.

Its walker already handles the aliased and side-effect import shapes this PR's second commit added, so nothing here adds coverage #18814 lacks.

The one piece #18814 didn't touch — the test and the cadence benchmark still resolving the constant through the Node-only reader — is split out into #18819. Closing.
