### PR TITLE
fix(browser): keep cookie-import warnings readable from newer hosts

### PR DESCRIPTION
**Pull request by brennanb2025**
| | Files | Added | Deleted | Net |
| :--- | ---: | ---: | ---: | ---: |
| Test | 1 | $\color{#1a7f37}{\Huge{\mathbf{+}}}$​80 | 0 | $\color{#1a7f37}{\Huge{\mathbf{+}}}$​80 |
| Prod | 2 | $\color{#1a7f37}{\Huge{\mathbf{+}}}$​46 | $\color{#cf222e}{\Huge{\mathbf{−}}}$​2 | $\color{#1a7f37}{\Huge{\mathbf{+}}}$​44 |

## Problem

`formatCookieImportWarning` switches on `warning.code`, and inside `cookies-undecryptable` on `warning.reason`, with explicit cases only and no fallback. TypeScript believes both switches are exhaustive because each union is closed at compile time. They are not exhaustive at runtime.

The summary crosses the runtime RPC wire — `store/slices/browser.ts` → `orca-runtime-browser.ts` — and the response is **cast, not decoded** (`runtime/runtime-rpc-client.ts:91`, `response as RuntimeRpcResponse<TResult>`). A newer remote host that publishes a fourth `reason` (or a third `code`) therefore reaches an older client, nothing matches, the function returns `undefined`, and `emitBrowserCookieImportToast` renders `toast.warning(undefined)` — a **blank warning toast** on a partly-failed import.

This is a regression from #14683: the original code had a `default:` arm that absorbed unknown reasons, and it was replaced with `case 'unknown':` to satisfy `switch-exhaustiveness-check`.

## Why not just restore `default:`

`typescript/switch-exhaustiveness-check` is configured with `allowDefaultCaseForExhaustiveSwitch: false` in both `.oxlintrc.json` and `config/oxlint-code-quality-type-aware.json`. Verified directly — adding a `default:` arm produces:

```
src/renderer/src/lib/browser-cookie-import-toast.ts:56:9: error typescript(switch-exhaustiveness-check):
  The switch statement is exhaustive, so the default case is unnecessary.
```

## Fix

A runtime guard **before** each switch. The incoming value is widened to `string`, checked against the set of variants this build actually handles, and anything else routes to a generic message. The switches stay exhaustive over the narrowed union, so the lint gate stays satisfied.

The handled sets are `Record<Union, true>` keyed by the unions themselves, so this **strengthens** rather than weakens the compile-time guarantee. Adding a fourth reason to `BrowserCookieImportSummary` breaks the build here in two places:

```
browser-cookie-import-toast.ts(17,7): error TS2741: Property '"hardware-token-required"' is missing in type
  '{ 'app-bound-encryption': true; 'linux-keyring-unavailable': true; unknown: true; }'
  but required in type 'Record<...>'.
browser-cookie-import-toast.ts(31,67): error TS2366: Function lacks ending return statement
  and return type does not include 'undefined'.
```

## Fallback copy

Neither message claims a cause it cannot know, and both give the user something to do:

- **Unknown reason** (we do know the cookies failed to decrypt, and how many): _"{{value0}} cookies could not be decrypted and were skipped for a reason this version of Orca does not recognize. Update Orca to see the details, then try the import again."_
- **Unknown code** (we know only that the import was degraded): _"The cookie import finished with a warning this version of Orca does not recognize. Update Orca to see the details, then check this profile before relying on its cookies."_

Both go through `translate()` like their neighbours; `en.json` synced via `pnpm run sync:localization-catalog`.

## Test evidence — red before, green after

Four tests feed a `reason` and a `code` outside the declared unions, cast at the test boundary since the point is that the wire can carry them. Two cover unrecognized string values; two cover non-string values (for example `['unknown']`), which an independent review found still slipped through — `Object.hasOwn` coerces its key, so an array whose `toString()` matches a handled variant passed the first version of the guard and fell straight back out of the switch.

**Against unmodified main (`b6d5972ec4`):**

```
 ❯ src/renderer/src/lib/browser-cookie-import-toast.test.ts (8 tests | 2 failed)
     × still warns when a newer host sends an undeclared undecryptable reason
     × still warns when a newer host sends an undeclared warning code

AssertionError: expected 'undefined' to be 'string' // Object.is equality
Expected: "string"
Received: "undefined"

 Test Files  1 failed (1)
      Tests  2 failed | 6 passed (8)
```

**After the fix:**

```
 Test Files  1 passed (1)
      Tests  8 passed (8)
```

## Gates

| Gate | Result |
| --- | --- |
| `node config/scripts/check-changed-code-quality.mjs` | `Changed-code quality gate passed since b6d5972ec453.` — 0 findings on all three scans |
| `pnpm run typecheck` | clean |
| vitest (affected files, `--config config/vitest.config.ts`) | 202 files / 1399 tests passed |
| `verify:localization-catalog` | `Verified 12231 localization key references against en.json.` |
| `verify:localization-extraction` | passed |
| `verify:localization-coverage` | `Localization coverage check passed with 12 allowlisted candidates.` |

All three oxlint scans were proven **live**, not silently dead, by injecting violations and confirming each caught them:

```
code quality:            no-else-return + no-unneeded-ternary  → 2 findings
type-aware code quality: switch-exhaustiveness-check           → 1 finding
React Doctor:            effect-needs-cleanup                  → 1 finding
```

## Scope

Three files. No refactor of the toast module, no renames, no changes to the cookie-import main-process code.

### CODE REVIEW

**Comment by brennanb2025** [comment]
## Review loop — CLEAN at `d713ce14ab`

Independent reviewer, fresh worktree off this branch, two passes. **Pass 2 changed nothing**, so the current head is the head a clean pass covers.

### Pass 1 — P1 found and fixed

The fix for the blank toast still had a blank-toast hole.

`Object.hasOwn` **coerces its key**. The guards took `code: string` / `reason: string`, so a value the compiler never saw — say `reason: ['unknown']`, whose `toString()` is `'unknown'` — passed the membership check, fell out of the switch, and rendered `toast.warning(undefined)`: exactly the bug this PR exists to fix.

```js
Object.hasOwn({ unknown: true }, ['unknown'])   // true
```

Fixed to take `unknown` and check `typeof` first, matching repo precedent (`isTopLevelView`, `isTuiAgent` both narrow from `unknown`):

```ts
function isHandledUndecryptableReason(reason: unknown): reason is UndecryptableReason {
  return typeof reason === 'string' && Object.hasOwn(HANDLED_UNDECRYPTABLE_REASONS, reason)
}
```

Two more tests added, proven red against this PR's own source before the fix. Pushed as `d713ce14ab`.

### Claims verified rather than assumed

- Both original holes close, checked across a hand-built 24-shape matrix over the two switches.
- All 8 pre-existing warning shapes produce **byte-identical** output — no regression in the working paths.
- The compile-time guarantee genuinely doubles: a 4th reason and a 3rd code each produce **TS2741** on the `Record` *and* **TS2366** on the switch. Re-verified after the P1 change, by adding a member and watching the build break.
- The PR's original two tests are red against main's source file alone.

### Gates

| gate | result |
|---|---|
| `config/scripts/check-changed-code-quality.mjs` | exit 0 — 0/0/0, and all three scans **proven live by injection** (2/1/1 findings caught) |
| `pnpm run typecheck` | exit 0 |
| vitest | 585 files, 5419 passed |
| localization ×3 | exit 0 |
| CI | 44 pass, 0 fail |

### Same defect class found elsewhere — reported, not fixed here

`src/renderer/src/lib/folder-workspace-path-status.ts:11` and `:39` switch on `status.reason` off the same cast wire (`repos.ts:1658`, `:2580`). An unrecognized reason returns `undefined`, and `FolderPathStatusIndicator.tsx:20` treats that as "nothing to show" — so the **broken-folder marker disappears entirely** and a broken folder workspace renders as healthy. Worse than the blank toast, since the warning is lost rather than merely empty. Two other same-shaped switches were checked and cleared: their discriminants are computed locally.

Deliberately left for a separate change — see below.

### Structural note

`src/shared/runtime-rpc-envelope.ts:26` declares `result: z.unknown()` inside the zod-validated success envelope, and `unwrapRuntimeRpcResult` returns it as `TResult` with no decode. So the envelope is validated and the payload is asserted — across **277 `callRuntimeRpc<…>` call sites in 72 files**. There is also no `assertNever`/`softAssertNever` helper in the tree, which is why this guard sits before the switch instead of in a default arm — the shape that produced the P1 above.

This PR is the right local fix. The recurring class wants a decode at the transport boundary, which is a separate piece of work.
