### ISSUE TITLE
[Bug]: Windows main process crash — Cannot find module 'qrcode' (regression from #9700 fix)

### ISSUE THREAD

**Issue by lucasung-debug** [stablyai/orca#10701]
### Operating system

**Comment by nwparker** [comment]
## Repro status: **skipped (environment blocked)**

Windows main-process crash missing `qrcode` module — packaging/runtime regression specific to Windows install path.

Not labeling `cannot_repro` — needs the blocked environment to attempt a full repro.
