### PR TITLE
feat(sidebar): one hover card for a session row, instead of four tooltips

### LINKED ISSUE #21691: [Feature]: the sidebar session row explains itself through the OS tooltip, not a hover card
### Problem or use case

A session row in the worktree sidebar explains itself through the operating system's tooltip. The row's text goes into the native `title` attribute, so the agent's reply shows up as a grey OS blob with raw markdown in it: asterisks, backticks and list dashes, unrendered.

It is also not one hover but four. The state dot has its own tooltip, the agent icon another, the model chip a third, and the row text the native one. Hovering different parts of the same row gives you different content, in different styles, with different timing. The worktree title right above it already opens a proper hover card with the app's own styling, which makes the difference obvious.

Two smaller things in the same row:

- The hover tint stacks. The workspace card paints one tint and the nested session row paints another, at different strengths — the row's is about 1.25% and effectively invisible, so it is unclear which item is under the cursor.
- A session holding a message that was typed and never sent has no marker anywhere, so it is easy to forget once the row scrolls out of view.

The row truncates, and everything it truncates is reachable only through a tooltip the app does not control: it cannot render markdown, cannot carry an icon, cannot be clicked and does not follow the design system. `docs/STYLEGUIDE.md` already takes this position — `Tooltip` for naming an icon-only control, `HoverCard` for a rich preview, and the `title` attribute listed under what not to use.

Related: #18840 asks for the model and the timestamp to be hidden from the row because they eat its width and truncate the session name. That is the same wound from the other side.

### Proposed solution

Give the session row the same hover card the worktree title already uses, carrying what the row cannot fit:

- the workspace it belongs to: name, branch or path, repo, remote host, board status
- the work it is linked to: PR with its state and check colour, GitHub issue, Linear with its real state colour, Jira — each chip linking to the item, opening inside Orca where Orca can open it
- live ports, child workspaces, notes, last activity
- the session: agent, state, model, time, the prompt, and the assistant's reply rendered as markdown, plus the subagents it spawned

And, while the row is being touched: one hover highlight on the item under the cursor instead of two stacked tints, and a marker on a session that holds an unsent message.

### Alternatives or additional context

- Keeping the native tooltips and formatting them better is not possible: the `title` attribute has no styling surface.
- Reusing the title's hover card by sharing its open state was tried before and flickers — #9304, fixed in #9662 by un-sharing the two Radix roots.

Moving the metadata into a card also answers #18840 without removing information from the app.

I have this working locally and can open the PR.

### PR DESCRIPTION
**Pull request by luizhcastro**
## ELI5

Hovering a session in the sidebar used to show the operating system's own little grey tooltip with the agent's reply in it, asterisks and all. Now the row opens a proper card that says which workspace it belongs to, what work it is linked to, and what the session is doing, with the reply rendered as text you can actually read.

## What Changed

**Before.** A session row explained itself through four separate tooltips. The state dot had one, the agent icon had one, the model chip had one, and the row's text fell back to the native `title` attribute, which paints the OS tooltip: raw markdown, no formatting, none of the app's styling. Hovering different parts of the same row gave you different things.

**After.** The row opens one hover card, the same primitive the worktree title already used, with the workspace it belongs to and the session under the cursor:

- workspace name and branch (or path, for a folder workspace)
- board status with its own colour, repo, remote host, PR with the number and the check colour, GitHub issue, Linear with its real state colour, Jira, live ports, child workspaces, unread, pinned, rebase or merge in progress, notes, last activity
- the session: agent, state, model, time, the prompt, and the assistant's reply rendered as markdown; the subagents it spawned, capped at five with a count for the rest

The chips with a destination are buttons. A GitHub PR or issue opens inside Orca, a Linear issue opens its task page, a GitLab MR or a Jira issue opens in the browser. They reuse the handlers the title hover already had, so no new navigation path was invented.

Two other things the row could not say:

- **One hover wash instead of two.** The card and the nested rows each painted their own hover tint, stacked, at different strengths — the row's was 1.25%, effectively invisible. A card now yields its hover to the row under the cursor (`:not(:has(...))`) and both use the same mix, so exactly one thing highlights at a time. Selected rows and the full list's lineage rows keep their own fill.
- **A message typed and never sent is marked.** A pencil appears on a session holding unsent text. For the native chat this comes from the composer's own draft cache; for a TUI agent the pane reads its painted composer through the detector this repo already has (`detectTerminalComposerDraft`), which covers Claude Code and Codex.

`worktree-hover-card-body.tsx` crossed the 400-line limit once the grid was in it, so the fact grid moved to `worktree-hover-fact-grid.tsx`.

## Why

The row is where you look to know what is happening, and it truncates. Everything it truncates was reachable only through a tooltip the app does not control, which cannot render markdown, cannot carry an icon, and cannot be clicked. #18840 is the same wound from the other side: it asks to hide the model and the timestamp because they eat the row's width. Moving that information into a card is the version of that request which does not take information away.

Alternatives considered:

- **Keep the tooltips, just format them better.** Not possible; the native `title` attribute has no styling surface. The styleguide already names this: `Tooltip` for an icon label, `HoverCard` for a rich preview, and "title attr" is listed under what not to use.
- **Reuse the worktree title's hover card by sharing its open state.** #9304 was exactly this, and PR #9662 fixed it by un-sharing: two Radix roots on one boolean flicker. Each hover owns its own state here.
- **Re-query the caches from the card.** The PR resolution in `use-worktree-card-review-details.ts` carries the host scoping for SSH and remote worktrees; a second implementation would silently miss them. The card reads what the card controller already resolved, through a context, so a closed row costs nothing and the memoised row is untouched.
- **Read the unsent draft from the agent status store.** That store is fed by agent hooks, and an agent cannot report what the user typed and did not send. It stays user-input state in its own registry.

## Linked Issue

Fixes #21691

## Visual Proof

| Before | After |
| --- | --- |
| 1-before | 2-after |
| The OS tooltip: raw markdown, no styling, nothing clickable. | The hover card: the workspace, the linked work, and the reply rendered. |

<details>
<summary>The card in the running app, and a session with subagents</summary>

3-extra-app-completo

4-extra-subagentes

</details>

## Testing

Tested on macOS, in the dev app, against real Claude Code sessions (including the PR chip and its "PR merged · checks passing" tooltip).

Automated:

- `worktree-hover-card-body.test.tsx` — what the card shows, the title de-duplication, markdown only for an assistant reply, deep-linked chips as buttons, and a whole group for content that could blow the card open (a 300-character name with nothing to wrap at, a giant model id, twelve subagents)
- `worktree-hover-workspace-chips.test.tsx` — board status resolved from the user's own definitions; asleep only when nothing runs in the workspace
- `worktree-sidebar-hover-wash.test.ts` — the row's wash equals the card's, and neither touches a selected row
- `agent-unsent-draft.test.ts` — a burst of 25 keystrokes is one probe pass; a pane that cannot read itself never erases what it knew; sending retires the marker through one late look
- `terminal-composer-draft-probe.test.ts` — against a real xterm with a Claude composer painted into it, including the placeholder that must not count as a message
- `agent-unsent-draft-wiring.test.ts` — both user-input paths still ask for the check. This one exists because the first version was hooked to a path typing does not use, so the marker never appeared; manual testing caught it, no test did.
- `tests/e2e/sidebar-agent-hover-card.spec.ts` — the real Radix card opening over a seeded session, and a second case measuring that pathological content cannot grow the card's box

Cross-platform: CSS only for the wash (`:has()` is Chromium, which is what Electron ships), no paths, no shortcuts. SSH and remote: the card reads the controller's already host-scoped values, and the unsent-draft probe reads the pane's own painted screen, so a remote session behaves like a local one. Performance: a closed row subscribes to nothing; the buffer read happens at most once per burst of input and only in a visible pane; the registry writes only on a change, so a row re-renders only when its own pane flips; nothing is written to the zustand store, which would wake every subscriber.

- [x] I manually tested these changes locally
- [x] Automated tests added/updated, or explained why not below

## AI Disclosure

Written with Claude Code (Opus 5).

## Agent skill upstream boundary

- [x] Not applicable, or this change follows `docs/reference/agent-skill-sharing-upstream-boundary.md` and copies or mechanically translates no upstream skill-installer source, tests, fixtures, registry entries, path tables, comments, or documentation.

## Notes

Ensure no issues in: Security, Cross-platoform support (Linux, Windows, Mac), Remote SSH, Mobile, general backwards compatibility, performance

Known limits, stated rather than hidden: the unsent-draft marker in a terminal only lights for the composers the repo's detector knows (Claude Code, Codex) — any other agent answers false rather than guess; the flag lives in memory, so restarting the app clears it while the text stays in the agent's composer; dirty file count and ahead/behind were left out of the card because they would add IPC inside a hover.

## Checklist

- [x] This PR is small and focused
- [x] I explained what changed and why (ELI5, the user-facing before/after, the mechanism, and why over the alternatives)
- [x] Before/after screenshots or videos attached for UI changes, or `N/A` with reason
- [x] Self-reviewed for correctness, security, and performance
- [x] Cross-platform, SSH/remote, and path/shortcut impact considered (or N/A)
- [ ] `pnpm lint`, `pnpm typecheck`, `pnpm test`, and `pnpm build` pass (or CI will cover; local preferred)

Ran locally: `pnpm lint` (full) and `pnpm typecheck` green, both e2e specs green, and the full `pnpm test` — 84594 passed, with 16 failures in 6 files, none of them from this change:

- `src/main/browser/browser-manager-viewport-ownership.test.ts` and `config/scripts/skill-recipe-shell.test.mjs` fail the same way on the base commit (`0817476`), which I checked out and re-ran to be sure
- `src/main/claude/claude-structured-real-cli.test.ts` compares the real CLI's skill list against this machine's, which has personal skills installed
- `tests/e2e/relay-region-correction.unit.test.ts` cannot resolve `pg` from `cloud/`, not installed here
- `tests/e2e/cross-version-wire/orchestration-delivery-downgrade.unit.test.ts` timed out under the full run's load and passes on its own
- `config/scripts/build-native-for-platform.test.mjs` is a native-build stdout timing test, also load-sensitive

`pnpm build`: `build:desktop` green end to end (typecheck, relay, CLI, electron-vite, the skills-CLI runtime check, the projected web client and the mobile web bundle). `build:native` then fails on this arm64 machine linking the Swift helpers for x86_64 — the Command Line Tools' Swift libraries here are arm64-only (`ld: symbol(s) not found for architecture x86_64`). That is the cross-architecture toolchain the contributing guide points at, not this change, which touches no native code.

### CODE REVIEW

File: src/renderer/src/components/native-chat/native-chat-draft-cache.ts [hunk 1]
```diff
@@ -14,6 +15,9 @@ export function readNativeChatDraftCache(scopeKey: string): string {
 }
 
 export function writeNativeChatDraftCache(scopeKey: string, draft: string): void {
+  // The scope key is the pane key, so the sidebar can show that this pane holds
+  // an unsent message. Sending clears the draft, which clears the flag here too.
+  setAgentUnsentDraft(scopeKey, draft.trim() !== '')
```
[the remark this answers is not in the document]
Comment (luizhcastro) [reply src/renderer/src/components/native-chat/native-chat-draft-cache.ts]: Real bug, and the repro is exact. Fixed in dc3caf3 by tracking which producer holds something instead of one boolean per pane: `setAgentUnsentDraft(paneKey, source, unsent)` with `'native-chat' | 'terminal'`, and `hasAgentUnsentDraft` reading the union. A listener still hears only when that union changes, so the row's re-render behaviour is unchanged. Two tests cover it: the TUI reporting empty cannot clear a waiting native draft, and both have to clear before the pane reads clean.

On the lifetime mismatch, you were right about one half and the other is deliberate:

- The cache eviction was a real phantom. `setBoundedScopeCacheEntry` now takes an optional `onEvict`, and the draft cache clears the `native-chat` source for any scope it sheds. Covered by a test that fills past `NATIVE_CHAT_COMPOSER_SCOPE_CACHE_MAX`.
- `unregisterAgentUnsentDraftProbe` not clearing the flag is intentional. A pane unmounts on hibernation and on a TUI/GUI toggle while the text stays in the agent's composer, so forgetting it there would be the lie. The probe answers `null` for what it cannot read, and only a producer that can see its own composer retires its own source.

File: src/renderer/src/components/sidebar/worktree-card-compact-agent-row.tsx [hunk 2]
```diff
@@ -264,6 +271,33 @@ export const CompactAgentRow = React.memo(function CompactAgentRow({
...
+                'inline-flex shrink-0 items-center',
+                isFocusedPane ? 'text-foreground/70' : 'text-muted-foreground/70'
+              )}
+              aria-label={translate(
+                'auto.components.sidebar.worktree.card.compact.agents.unsentDraft',
+                'Message typed but not sent'
+              )}
+              data-agent-unsent-draft="true"
+            >
+              <PencilLine className="size-2.5" aria-hidden />
```
[the remark this answers is not in the document]
Comment (luizhcastro) [reply src/renderer/src/components/sidebar/worktree-card-compact-agent-row.tsx:291]: Fixed in dc3caf3: the marker span carries `role="img"`, so its `aria-label` is the element's accessible name. Kept the label over `sr-only` text because the row is a single 24px line and the neighbouring state indicators use the same shape (`ReviewPill` in `AgentKanbanCard.tsx` labels a `role="img"` span). Its unit test asserts the label and that the marker still carries no native `title`.

File: src/renderer/src/components/sidebar/worktree-hover-facts.ts [hunk 3]
```diff
@@ -0,0 +1,67 @@
...
+
+/** Title of the linked work item, when it says something the card doesn't already. */
+export function getWorktreeHoverContextTitle(
+  facts: WorktreeHoverFacts,
+  ...alreadyShown: (string | undefined)[]
+): string | null {
+  const taken = new Set(
+    [facts.title, ...alreadyShown].map((value) => value?.trim()).filter(Boolean)
+  )
+  const candidates = [facts.review?.title, facts.linearIssue?.title, facts.issue?.title]
```
[the remark this answers is not in the document]
Comment (luizhcastro) [reply src/renderer/src/components/sidebar/worktree-hover-facts.ts]: Good catch, fixed in dc3caf3. `getWorktreeHoverContextTitle` now considers `facts.jiraIssue?.title` after the PR, Linear and GitHub issue titles, so a workspace whose only linked item is a Jira issue still gets that context line.

File: src/renderer/src/components/terminal-pane/terminal-composer-draft-probe.ts [hunk 4]
```diff
@@ -0,0 +1,24 @@
...
+ * Claude Code and Codex today. Any other agent answers false rather than guess.
+ */
+export function readTerminalComposerDraftPresence(terminal: Terminal): boolean | null {
+  // Why: a pane detached from the DOM has no painted screen to read, and its
+  // buffer may be mid-replay — answering would be a coin flip, so say nothing.
+  if (!terminal.element?.isConnected) {
+    return null
+  }
+  const draft = detectTerminalComposerDraft(readTerminalCursorLineContext(terminal, terminal.rows))
+  return (draft?.text.trim().length ?? 0) > 0
```
[the remark this answers is not in the document]
Comment (luizhcastro) [reply src/renderer/src/components/terminal-pane/terminal-composer-draft-probe.ts]: Right, and it is the same rule I applied to a detached pane one line above. Fixed in dc3caf3: a null cursor context returns null rather than false, so the registry keeps the last known answer. I also made the parameter structural (`TerminalComposerDraftSource`) so a test can hand it an unreadable screen without an xterm, and added that case.

File: src/renderer/src/i18n/locales/en.json [hunk 5]
```diff
@@ -5650,6 +5650,16 @@
           "d1113f4660": "Failed to open browser",
           "fed49903c9": "{{value0}} live {{value1}}"
         },
+        "worktreeHoverCard": {
+          "asleep": "Sleeping",
+          "childWorkspaces": "{{count}} child workspaces",
```
[the remark this answers is not in the document]
Comment (luizhcastro) [reply src/renderer/src/i18n/locales/en.json]: Fixed in dc3caf3 with `childWorkspaces_one` and `childWorkspaces_other`. One note for anyone doing this next: `verify:localization-catalog` wants every key it can see statically, so calling the base key and letting i18next resolve the suffix fails the gate. The call site picks the form explicitly, the way `AgentKanbanCard.tsx` does for its subagent count.

File: src/renderer/src/components/sidebar/worktree-card-compact-agent-hover.tsx [hunk 6]
```diff
@@ -0,0 +1,109 @@
...
+  // asterisks the card exists to render. Warm it while the row is on screen.
+  React.useEffect(() => {
+    if (secondaryIsAssistantMessage) {
+      preloadCommentMarkdown()
+    }
+  }, [secondaryIsAssistantMessage])
+
+  return (
+    <HoverCard openDelay={100}>
+      <HoverCardTrigger asChild>{children}</HoverCardTrigger>
```
[the remark this answers is not in the document]
Comment (luizhcastro) [reply src/renderer/src/components/sidebar/worktree-card-compact-agent-hover.tsx:68]: Not taking this one, and I want to be explicit about why rather than silently skipping it.

The compact agent row was already a non-focusable `<div>` with an `onClick` before this PR; wrapping it in `HoverCardTrigger asChild` changes nothing about that. So this is a pre-existing accessibility gap, not a regression here.

Fixing it properly is a navigation decision, not a one-line addition:

- Keyboard activation in this list lives at the worktree-row level. The compact row exists inside it and deliberately stops Enter/Space from reaching the list — see `stopActivationKeyPropagation` in `worktree-card-compact-agent-row.tsx`, which is there so focused nested buttons keep those keys local. Giving the row its own handler has to be reconciled with that, not bolted next to it.
- Adding `tabIndex` makes every session row a tab stop, so a sidebar with ten workspaces and their sessions becomes dozens of stops before the content area. That is a roving-tabindex / arrow-key problem, which is how the rest of this list would want to solve it.
- Radix opens a hover card on trigger focus, so once the row is focusable the card also becomes keyboard-reachable — which is the payoff, and another reason to do it deliberately.

Happy to do it as a follow-up if the maintainers want session rows in the keyboard path; it belongs in its own PR with the arrow-key behaviour, not in one about the hover card.

**Comment by luizhcastro** [comment]
@coderabbitai resolve
