### PR TITLE
fix(e2e): restore the helpers the macOS key-remap spec imports

### PR DESCRIPTION
**Pull request by nwparker**
## What

`tests/e2e/terminal-macos-system-key-remap.spec.ts` imports three modules that are not in the repo:

- `./terminal-ime-pane-arena`
- `./terminal-ime-cdp-composition`
- `./terminal-ime-platform-policy`

#13314 added the spec, and its final commit — `chore: drop non-mergeable IME e2e scratch files` — deleted the three helpers. The spec was left behind.

## Why it matters more than one spec

Playwright resolves every spec before running any of them, so an unresolved import is fatal for the entire run rather than for the one file. On `main` today:

```
$ npx playwright test --config tests/playwright.config.ts --project=electron-headless --list
Error: Cannot find module './terminal-ime-pane-arena'
   at terminal-macos-system-key-remap.spec.ts:37
Total: 0 tests in 0 files
```

`playwright.config.ts` matches `**/*.spec.ts` with no `testIgnore`, so all ten scheduled E2E shards have been failing at collection since #13314 merged, and the macOS system-key-remap coverage the PR existed for has never run.

It stayed invisible because no `tsconfig` project includes `tests/`, so `pnpm run typecheck` never sees these imports, and PR E2E is advisory (`e2e` is deliberately absent from `verify`'s `needs`).

## Change

Restored from `56bf4a24758^`, the commit before the drop:

- `terminal-ime-pane-arena.ts` and `terminal-ime-platform-policy.ts` — verbatim; every export is used by the surviving spec.
- `terminal-ime-cdp-composition.ts` — only the four entry points this spec imports (`ImeKeyIdentity`, `dispatchImeRewrittenPrintableKey`, `dispatchImeSubstitutedTextKey`, `dispatchPlainEnter`). The dropped exports drove composition sessions for specs that were never merged, so bringing them back would be dead code. The module doc is retargeted to what remains.

All dependencies (`helpers/store`, `helpers/terminal`, `terminal-ime-boundary-probe`, `terminal-ime-byte-reader`) are already on `main`.

## Verification

Collection restored:

```
Total: 528 tests in 222 files
```

The spec itself, run locally on macOS:

```
Running 6 tests using 1 worker
  ✓ sends ` for the 두벌식 backquote key when a system remap rewrites it to a backquote (6.7s)
  ✓ sends ₩ for the 두벌식 backquote key when no remap is installed (6.2s)
  ✓ sends ₩ for the 두벌식 backquote key when a system remap substitutes it for itself (5.2s)
  ✓ sends ` for the 세벌식 최종 backquote key when a system remap rewrites it to a backquote (6.1s)
  ✓ sends * for the 세벌식 최종 backquote key when no remap is installed (5.2s)
  ✓ sends * for the 세벌식 최종 backquote key when a system remap substitutes it for itself (5.3s)
  6 passed (42.2s)
```

`oxlint tests/` and `check:reliability-gates` are clean.

Note: this PR touches no `*.spec.ts`, so `e2e-paths` in `pr.yml` will skip the advisory E2E job. A full `e2e.yml` run is dispatched against this branch separately to confirm collection and these six tests on the Linux runners.

## Scope

This restores collection. It does not claim the full suite is green — `pr.yml` records that it is red on `main` for other reasons, and flipping the merge gate on is a separate call.

Made with [Orca](https://github.com/stablyai/orca) 🐋

### CODE REVIEW

**Comment by nwparker** [comment]
## Linux CI validation

Dispatched a full `e2e.yml` run against this branch (the advisory PR job skips, since no `*.spec.ts` changed): https://github.com/stablyai/orca/actions/runs/31466056397

**Collection is fixed on Linux.** All ten shards executed tests instead of dying at load, and `build e2e app` + `ssh docker watcher isolation` are green.

The restored spec passes on the Linux runners, shard 7:

```
✓ 35 … sends ` for the 두벌식 backquote key when a system remap rewrites it to a backquote (16.2s)
✓ 36 … sends ₩ for the 두벌식 backquote key when no remap is installed (16.4s)
✓ 37 … sends ₩ for the 두벌식 backquote key when a system remap substitutes it for itself (16.4s)
✓ 38 … sends ` for the 세벌식 최종 backquote key when a system remap rewrites it to a backquote (16.3s)
✓ 39 … sends * for the 세벌식 최종 backquote key when no remap is installed (16.3s)
✓ 40 … sends * for the 세벌식 최종 backquote key when a system remap substitutes it for itself (16.3s)
```

That confirms the UA-override in `terminal-ime-platform-policy` carries the macOS ownership decision on a Linux runner, which is what the helper exists for.

## Remaining suite failures are pre-existing

Six shards are red — 11 tests across 10 specs, none of them IME-related and none importing the restored helpers:

- `artificial-opencode-terminal-load.spec.ts` — ACK-backpressured hidden model output
- `browser-local-https-certificate-trust.spec.ts`
- `floating-tab-rename.spec.ts`
- `github-created-issue-start-prefill.spec.ts`
- `repro-7732-gitlab-checks-job-details.spec.ts`
- `ssh-config-host-import.spec.ts` (P6 and P7)
- `tab-create-entry-file-paths.spec.ts`
- `terminal-hidden-view-parking.spec.ts` — 25-cycle byte-for-byte static frame
- `voice-microphone-selection.spec.ts`
- `worktree-jump-palette-filter.spec.ts`

This is the redness `pr.yml` already records as the reason `e2e` is kept out of `verify`'s `needs`. It could not be observed while collection returned zero tests, so this PR does not fix it — it makes it visible and actionable again. Net: 0 tests running → ~517 passing, 11 failing.

PR checks: 44/45 pass, `e2e` skipping as expected.
