### PR TITLE
fix(test): unbreak main typecheck in local-pty-shell-ready.test.ts

### PR DESCRIPTION
**Pull request by brennanb2025**
## Problem

`main` fails `pnpm typecheck` since #8025 landed:

```
src/main/providers/local-pty-shell-ready.test.ts(886,57): error TS2345: Argument of type '"-l"' is not assignable to parameter of type '"-i"'.
```

Every open PR's `verify` check now fails on the merge ref regardless of the PR's own contents (first seen on #8016's CI; reproduced on pristine `origin/main`).

## Cause

The `as const` on the zsh arg-variant loop narrows `args` to `readonly ['-i'] | readonly ['-l', '-i']`, so `args.includes('-l')` is a type error on the `['-i']` member — `Array.prototype.includes` only accepts the tuple's element type.

## Fix

Drop the `as const` so the literal infers `string[][]`. Nothing in the loop relies on tuple types (`join`, spread, `includes` only). No runtime behavior change; all 66 tests in the file still pass, full `pnpm typecheck` green.

Made with [Orca](https://github.com/stablyai/orca) 🐋

### CODE REVIEW

**Comment by brennanb2025** [comment]
Superseded — main was fixed by the positional-check change that landed in #7544 (`args[0] === '-l'` keeps the `as const`). Verified current main tip typechecks clean. Closing.
