### PR TITLE
fix(lint): exempt the descendant-sweep test shim from the module-mocking gate

### PR DESCRIPTION
**Pull request by Jinwoo-H**
| | Files | Added | Deleted | Net |
| :--- | ---: | ---: | ---: | ---: |
| Test | 0 | 0 | 0 | 0 |
| Prod | 1 | $\color{#1a7f37}{\Huge{\mathbf{+}}}$​9 | 0 | $\color{#1a7f37}{\Huge{\mathbf{+}}}$​9 |

Main's static-analysis job fails on every PR since #20642 / #20645 merged: their two `mock-descendant-sweep.ts` files (daemon and relay) are test-only side-effect shims whose whole body is one `vi.mock`, and the anti-slop `no-module-mocking` gate only exempts `*.test.ts`, `*.spec.ts`, `tests/**` and `__mocks__/**`. Their CI ran before the gate landed.

```
src/relay/mock-descendant-sweep.ts:4:1: error anti-slop(no-module-mocking)
src/main/daemon/mock-descendant-sweep.ts:4:1: error anti-slop(no-module-mocking)
```

Fix: a file-scoped exemption for `**/mock-descendant-sweep.ts`, in the same form as the config's existing ones (the root lint scan does not load the plugin, so an inline directive reads back as unused). The shim is imported by 60 suites and by no product code; the alternative is inlining the same hoisted factory in each of them.

Verified locally: the exact CI command passes on this branch and fails on `origin/main`.

### CODE REVIEW

File: config/oxlint-anti-slop.json [hunk 1]
```diff
@@ -56,6 +56,15 @@
         "anti-slop/no-module-mocking": "off"
       }
     },
+    // mock-descendant-sweep.ts (daemon and relay) is a test-only side-effect shim: its whole body
+    // is one vi.mock that keeps mock PTY PIDs away from the host process table, and it exists so
+    // 60 suites do not each inline the same hoisted factory. It is never imported by product code.
+    {
+      "files": ["**/mock-descendant-sweep.ts"],
+      "rules": {
+        "anti-slop/no-module-mocking": "off"
```
[the remark this answers is not in the document]
Comment (Jinwoo-H) [reply config/oxlint-anti-slop.json:65]: Not the case here: the exact CI command (`oxlint --config config/oxlint-anti-slop.json src config tests mobile --deny-warnings`) fails on `origin/main` with the two shim errors and passes on this branch, and the config's existing overrides (`**/test-support/rpc-recording/**`, `**/browser-pane/annotate/**`) already match files under `src/` and `mobile/` in the same way. A leading `**/` matches at any depth regardless of the config directory.
