### ISSUE TITLE
Linux from-source: blank white window from Node process/promisify in sandboxed renderer

### ISSUE THREAD

**Issue by jondmarien** [stablyai/orca#18812]
## Summary

Building and launching Orca from source on Linux (Electron sandboxed renderer) can show a blank white main window.

Console:
```
Uncaught ReferenceError: process is not defined
Uncaught TypeError: promisify is not a function
```

## How we found it

Smoke-testing from-source Orca on Omarchy (Arch, Wayland) with Electron 43. Separately, Wayland can hit Chromium GPU FATAL/SIGILL without X11/no-sandbox/disable-gpu flags (environmental, out of scope). With a surviving GPU path, the window stayed white due to the renderer importing process-table-snapshot-reader (Node promisify/execFile + module-load process.platform) only to read a 500ms TTL constant.

## Root cause

- sandbox:true renderer has no Node process
- agent-completion-poll-interval.ts imports PROCESS_TABLE_SNAPSHOT_MAX_STALENESS_MS from process-table-snapshot-reader.ts
- Introduced in #18742

## Related

Fork proof: https://github.com/jondmarien/orca/pull/9

**Comment by jondmarien** [comment]
Fixed by https://github.com/stablyai/orca/pull/18814 — closing this duplicate. Thanks!
